apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-volume-claim
spec:
  storageClassName: rook-cephfs-east
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
