---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: "us-west-2"
  version: "1.21"

availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]

managedNodeGroups:
  - name: nodegroup
    desiredCapacity: 3
    instanceType: t3.small
  - name: gpu-pool
    desiredCapacity: 1 
    instanceType: p3.2xlarge
    volumeSize: 20
    labels:
      accelerator: 'nvidia' 
